### ISSUE TITLE
Not all incompatible variants of a package are detected

### ISSUE THREAD

**Issue by jkloetzke** [BobBuildTool/bob#174]
Not all conditions of incompatible variants are detected. Consider the following recipe:

```yaml
multiPackage:
    "":
        root: True

        depends:
            - name: root-lib
              environment:
                FOO: bar
            - name: root-lib
              use: [tools]
              environment:
                FOO: baz

        buildScript: "true"
        packageScript: "true"

    lib:
        packageVars: [FOO]
        packageScript: "true"
        provideTools:
            t: "."
```

This should fail because `FOO` is used in `root-lib` and has two distinct values. But it does not trigger until the `use: [tools]` is removed.
