### ISSUE TITLE
Wrong error message on pure SCM checkouts

### ISSUE THREAD

**Issue by jkloetzke** [BobBuildTool/bob#186]
Imagine the following defunct simple recipe:

```yaml
root: True
checkoutSCM:
   scm: url
   url: https://bob.test/does-not-exist.tgz
buildScript: "true"
packageScript: "true"
```

Building it fails expectedly but the error message is misleading:

```
curl: (6) Could not resolve host: bob.test
Step failed with return status 6; Command: curl -sSgLf -o $F https://bob.test/does-not-exist.tgz
Call stack (most recent call first)
    #0: Bob prolog, line 46, in main
Step failed with return status 6; Command: ( F=$(mktemp); trap 'rm -f $F' EXIT; set -e; curl -sSgLf -o $F https://bob.test/does-not-exist.tgz; mv $F does-not-exist.tgz )
Call stack (most recent call first)
    #0: Bob prolog, line 49, in main
Build error: Build script ./dev/src/root/1/checkout.sh returned with 6
```

The error should be flagged inside "Recipe root" not in "Bob prolog".
