### ISSUE TITLE
Multiple sandboxes not properly supported

### ISSUE THREAD

**Issue by jkloetzke** [BobBuildTool/bob#239]
The following recipe `t.yaml` fails on `bob build t-outside` (given `bobMinimumVersion: "0.15"` in config.yaml) because the artifact is not built in the different sandboxes as expected.

```yaml
multiPackage:
  sandbox:
    multiPackage:
      "1":
        packageScript: |
            echo sandbox-1 > id.txt
      "2":
        packageScript: |
            echo sandbox-2 > id.txt
    provideSandbox:
      paths: ["/bin", "/usr/bin"]
      mount:
        - "/bin"
        - "/dev"
        - "/etc"
        - "/lib"
        - "/lib64"
        - "/proc"
        - "/usr"

  inside:
    multiPackage:
      "1":
        depends:
          - name: t-sandbox-1
            use: [sandbox]
      "2":
        depends:
          - name: t-sandbox-2
            use: [sandbox]
    fingerprint: "cat /id.txt"
    packageScript: |
      cp /id.txt .

  outside:
    root: true
    depends:
      - t-inside-1
      - t-inside-2
    buildScript: |
      if cmp "$2/id.txt" "$3/id.txt" ; then
        echo "Sandbox id's are NOT different!" >&2
        exit 1
      fi
```

In this recipe the `fingerprint` indicates that the artifacts depend on the host environment. As two different sandboxes are used the `t-inside-1` and `t-inside-2` packages must be built separately.
