### ISSUE TITLE
GitSCM: "tag:" now adds "tags/" for checkout step

### ISSUE THREAD

**Issue by kolewu** [BobBuildTool/bob#31]
In e3d254c546 there is an additional change that adds `"tags/"` to the parameter given by `tag:`.

We use the `tag` parameter of _GitScm_ to get the branch, tag or commit from a multipackage with a variable:

```yaml
checkoutSCM:
    scm: git
    url: git@git.url:example/example_common.git
    tag: ${SCM_REVISION}

multiPackage:
    lib-v2.3.0:
        root: true
        environment:
            SCM_REVISION: "v2.3.0"
```

Is there another way for doing this? It's a workaround to handle different versions of a package inside one recipe, to tackle the problem of recipe reuse.
