### ISSUE TITLE
bob - error: dependency must only be once

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#312]
Hey, 

the following scenario I would need:

```
root: True

depends:
    -
      name: toolchain::x86_64-linux #init a host environment
      use: [environment]
      forward: True
    -
      name: toolchain::lcov  #hosttool
      use: [tools]
      forward: True
    -
      name: toolchain::aarch64-linux #init the target environment
      use: [environment]
      forward: True
    -
      name: toolchain::lcov #environment variables like CXXFLAGS --coverage a.s.o
      use: [environment]
      forward: True
    - ...
```

if i would use 
```
    -
      name: toolchain::lcov
      use: [environment, tools]
      forward: True
```
in upper or lower position, i get a lcov for target or i lost the CXXFLAGS.
