### ISSUE TITLE
Support git shallow clones

### ISSUE THREAD

**Issue by jkloetzke** [BobBuildTool/bob#315]
The title says it all. And while we are at it we should add `--[no-]single-branch` support too. Probably done via a regular property:

```yaml
checkoutSCM:
    scm: git
    shallow: 42 / "YYYY-MM-DD"
    singleBranch: True
```

In a local project the user could set that via `scmOverrides` to speed up the checkout:

```yaml
scmOverrides:
    - match:
          scm: git
      set:
          shallow: 1
```
