### ISSUE TITLE
'scmOverrides' has an invalid type

### ISSUE THREAD

**Issue by Ferruck** [BobBuildTool/bob#348]
When trying to use the `scmOverrides` provided by the [latest online Bob docs](https://bob-build-tool.readthedocs.io/en/latest/manual/configuration.html#scmoverrides):

```yaml
scmOverrides:
  -
    match:
      url: "git@acme.com:/foo/repo.git"
    del: [commit, tag]
    set:
      branch: develop
    replace:
      url:
        pattern: "foo"
        replacement: "bar"
    if: !expr |
      "${BOB_RECIPE_NAME}" == "foo"
```

Bob fails with a `Parse error`:

```
Parse error: Error while validating user.yaml: setting 'scmOverrides' has an invalid type
```

The problem is "fixed" by removing the line containing `del`, but I remember that syntax working for me. Is this a regression?

```
$ bob --version
Bob version 0.17
```
