### ISSUE TITLE
Request: checksum file support

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#397]
sometimes there are checksum files next to download files, like .sha256 extended files.
it would be nice, if the following would be possible:

```
checkoutSCM:
    scm: url
    url: ${FILE_SERVER}/<library>-${PKG_VERSION}.tar.xz
    digestSHA1Url: ${FILE_SERVER}/<library>-${PKG_VERSION}.tar.xz.sha1
```

or: 

```
checkoutSCM:
    scm: url
    url: ${FILE_SERVER}/<library>-${PKG_VERSION}.tar.xz
    digestSHA256Url: ${FILE_SERVER}/<library>-${PKG_VERSION}.tar.xz.sha256
```

an example of current manual implementation:

```
    FILE_SERVER="https://github.com/bazelbuild/bazel/releases/download/${PKG_VERSION}/"

    if [ ! -f "bazel-${PKG_VERSION}-${PLATFORM:-linux}-${ARCH}${EXT:-}" ] ; then
        curl -LJO ${FILE_SERVER}/bazel-${PKG_VERSION}-${PLATFORM:-linux}-${ARCH}${EXT:-}
    fi
    if [ ! -f "bazel-${PKG_VERSION}-${PLATFORM:-linux}-${ARCH}${EXT:-}.sha256" ] ; then
        curl -LJO ${FILE_SERVER}/bazel-${PKG_VERSION}-${PLATFORM:-linux}-${ARCH}${EXT:-}.sha256
    fi

    SHA_EXP="$(head -n1 bazel-${PKG_VERSION}-${PLATFORM:-linux}-${ARCH}${EXT:-}.sha256)"
    SHA="$(sha256sum bazel-${PKG_VERSION}-${PLATFORM:-linux}-${ARCH}${EXT:-})"

    if [[ "${SHA_EXP//*//}" != "${SHA//*//}" ]] ; then
        echo "expected sha is ${SHA_EXP}, but got ${SHA}"
        exit 1
    fi
```
