### ISSUE TITLE
Environment is not properly "used"

### ISSUE THREAD

**Issue by Ferruck** [BobBuildTool/bob#398]
When trying a simple recipe like the following:

```yaml
inherit: ["basement::rootrecipe"]

depends:
    -
      name: devel::cross-toolchain-arm-linux-gnueabihf
      use: [environment, tools]
      forward: True

buildTools: [target-toolchain]
buildVars: [AUTOCONF_TARGET]
buildScript: |
    echo "${AUTOCONF_TARGET}"

packageScript: |
    echo "Done"
```

building fails with `/.script: line 47: AUTOCONF_TARGET: unbound variable` though `devel::cross-toolchain-arm-linux-gnueabihf` clearly defines it:

```yaml
[snip]

    # ARMv7 Linux CortexA toolchain with hard floating point
    arm-linux-gnueabihf:
        environment:
            AUTOCONF_TARGET: "arm-linux-gnueabihf"
            ARCH: "arm"
            GCC_TARGET_ARCH: "armv7-a"
            GCC_TARGET_FLOAT_ABI: "hard"
            GCC_TARGET_FPU: "vfpv4"
            GCC_LIBC: "glibc"

[snip]
```

Am I missing something? See the full recipe stack here: [recipes.tar.gz](https://github.com/BobBuildTool/bob/files/5970828/recipes.tar.gz)

`Bob version 0.18.2.dev50+g455a2ae`
