### ISSUE TITLE
environment variable in depens will not resolved

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#399]
```
depends:
# target toolchain
  -
    name: devel::cross-toolchain
    environment:
        AUTOCONF_TARGET: "${BLUB:-x86_64-bob-linux-gnu}" <-- doesn't work
        ARCH: "${BLA:-x86_64}" <-- doesn't work
        GCC_LIBC: glibc
        BASEMENT_OPTIMIZE: "s"
        BASEMENT_DEBUG: "0"
    use: [environment, tools]
    forward: True
```
