### ISSUE TITLE
multiple anonymous multiPackages

### ISSUE THREAD

**Issue by rhubert** [BobBuildTool/bob#402]
Having a recipe like

```yaml
root: True

packageScript: "true"

multiPackage:
   "":
      multiPackage:
         a:
            buildScript: |
               echo "a"
         b:
            buildScript: |
               echo "b"
   "":
      multiPackage:
         c:
            buildScript: |
               echo "c"
```

the first anonymous `multiPackage` - group is silently ignored. :( 

```
$ bob ls
root-c
```

**Comment by jkloetzke** [comment]
This is actually a bug in yaml/pyyaml#165. You should have gotten an error about the duplicate empty keys `""` at parse time. Did you actually want to define two anonymous `multiPackage` entries or was it just a mistake?

**Comment by rhubert** [comment]
I did some refactoring and wanted to use multiple anyonymouse `multiPackage`s to group packages sharing a common build script like this:

```yaml
root: True

packageScript: "true"

multiPackage:
   "":
      buildScript: |
           do_it
      multiPackage:
         a:
             depends:
                  - foo
         b:
             depends:
                  - bar
   "":
      buildScript: |
         do_something_else
      multiPackage:
         c:
            depends:
                - baz
```

Moving the `buildScript`s into functions avoids the need of multiple anonymous `multiPackage` use. Feel free to close this.
