### ISSUE TITLE
${BOB_TOOL_PATHS[target-toolchain]} in environment variables

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#481]
hi,

i want to use for a toolchain something like that:
```
provideTools:
  target-toolchain:
    path: "toolchain/bin"
    environment:
      CXXFLAGS: "--sysroot=${BOB_BOB_TOOL_PATHS[target-toolchain]} /../../rootfs"
```
but this will not parsed correctly, i guess because of `[` and `]`.
is this a bug? any better ideas to solve that?
