### ISSUE TITLE
bob rebuilds everytime if environment changed by bob -c

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#508]
hi, we are using `bob` with `-c` argument to set configurations like:

debug.yaml:
```yaml
environment:
    # default compile flags
    BASEMENT_OPTIMIZE: "0"      # compiler optimization level (0/1/2/s)
    BASEMENT_DEBUG: "1"         # generate debug symbols (0/1)
    BUILDENV_ENABLE_RPATH: "ON" # add rpath flags
```
and release.yaml:
```yaml
environment:
    # default compile flags
    BASEMENT_OPTIMIZE: "2" # compiler optimization level (0/1/2/s)
    BASEMENT_DEBUG: "1"    # generate debug symbols (0/1)
```

everytime if we switch the used config, bob has to rebuild everything. for the first build, that is reasonable, but if there was already a finished build, it would be cool, if that could be reused instead of rebuilding everything.
each rebuild will take 20 minutes.

we also tried the bob out-of-tree functionality, but there we have the sources twice, which is also not comfortable to use.
