### ISSUE TITLE
dependency environment issue

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#536]
hey,

this is working for `host-toolchain` (compat), but not for `target-toolchain` (cross):

```
depends:
    - environment:
          CXXFLAGS: "$CXXFLAGS something"
      depends:
          - libs....
```

**Comment by jkloetzke** [comment]
I guess this issue is for the basement project, isn't it?

The culprit looks to be that `recipes/devel/cross-toolchain.yaml` sets a fixed `CXXFLAGS` that is picked up by every package that uses the tool. Because the variable is defined by the tool environment, it overrides any inherited value of `CXXFLAGS`. In contrast, the host compat toolchain does not define any `CXXFLAGS` so you can set it freely.

AFAICT we have no provisions in the recipes to inject CXXFLAGS for dependencies that use a cross-toolchain.

**Comment by mahaase** [comment]
> I guess this issue is for the basement project, isn't it?

Not sure, because of:

> AFAICT we have no provisions in the recipes to inject CXXFLAGS for dependencies that use a cross-toolchain.

so maybe we need a way to inject environment stuff? the cross toolchain does not have the `-fPIC` flag, but i want to build python3 with something like this: 

```
depends:
  - environment:
      BASEMENT_LIBS: "static"
      CXXFLAGS: "$CXXFLAGS -fPIC"
    depends:
      - libs....
```
